# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Arash Javanmardi
title: Civil engineer, aspiring Datascientist
# email: aj.javanmardi@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Additional icon links
additional_links:
- title: LinkedOn
  icon: fab fa-linkedin
  url: https://www.linkedin.com/in/arash-javanmardi-9567b9167/
- title: Gitlab
  icon: fab fa-gitlab
  url: https://gitlab.rhrk.uni-kl.de/ajavanma
- title: Github
  icon: fab fa-github
  url: https://github.com/ajavanma
- title: Discord
  icon: fab fa-discord
  url: discordapp.com/users/570764982908878858
- title: Spotify
  icon: fab fa-spotify
  url: https://open.spotify.com/playlist/3QX1vJwNmFO5Uz9nWNRwUo?si=1aa4ac0b21e24f9f
- title: CV
  icon: fab fa-dropbox
  url: https://ajavanma.github.io/cv/cv_arash_javanmardi.pdf

# Google Analytics and Tag Manager
google_analytics: "UA-265902251-1"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Arash, a civil engineer researching computer vision.
  My distinctive trait is an insatiable fervour for obtaining knowledge.
  I find my purpose in understanding, pattern recognition and contributing to the collective corpus of wisdom.
  I consider myself privileged to have crossed paths with some extraordinary people who have inspired my passion and molded my identity.

# Footer
footer_show_references: true
references_title: aj.javanmardi@gmail.com

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
