# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Arash Javanmardi
title: Civil engineer, aspiring Datascientist
email: aj.javanmardi@gmail.com
# website: https://github.com/ajavanma/cv/cv_arash_javanmardi.pdf

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: twitter
linkedin_username: arash-javanmardi-9567b9167 
github_username:  ajavanma
# stackoverflow_username: "00000001"
# dribbble_username: 0
# facebook_username: 0
# flickr_username: 0
# instagram_username: 0
# xing_username: 0
# pinterest_username: 0
# youtube_username: 0
# googleplus_username: 0
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Gitlab
  icon: fab fa-gitlab
  url: https://gitlab.rhrk.uni-kl.de/ajavanma
- title: CV
  icon: fas fa-page
  url: https://ajavanma.github.io/cv/cv_arash_javanmardi.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Arash, a civil engineer researching computer vision.


content:
  - title: Experience 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  DFKI
        link: link
        # link_text: boringcompany.com
        sub_title: sub_title
        caption: Caption
        quote: >
          quote
        description: | # this will include new lines to allow paragraphs
          Description
          - layout: left
        title:  RPTU
        link: link
        # link_text: boringcompany.com
        sub_title: sub_title
        caption: Caption
        quote: >
          quote
        description: | # this will include new lines to allow paragraphs
          Description

  - title: Education 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RPTU
        caption: 2021 - 2023
        sub_title: M.Sc. Civil Eng.
        quote: >
          quote
        description: | # this will include new lines to allow paragraphs
          Description     

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Free Code Camp Certificates
        link: link
        link_text: Link Text
        additional_links:
          - title:  Machine Learning with Python
            icon: fab fa-free-code-camp
            # url: https://freecodecamp.org/certification/Javanmardi/machine-learning-with-python-v7 
        quote: >
          quote
        description: | # this will include new lines to allow paragraphs
          - https://freecodecamp.org/certification/Javanmardi/machine-learning-with-python-v7
          - https://freecodecamp.org/certification/Javanmardi/data-analysis-with-python-v7  
          - https://www.freecodecamp.org/certification/Javanmardi/scientific-computing-with-python-v7    

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hobbies:
      - Reading
      - Gaming
      - [link](https://www.youtube.com/)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme
# theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
